DELETE FROM GOODS;
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(100, 'ボールペン', 120, 'ACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(200, '鉛筆', 50, 'ACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(300, 'ノート', 460, 'ACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(400, 'メモ帳', 300, 'DEACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(500, 'りんご', 250, 'DEACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(600, 'ばなな', 350, 'DEACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(700, '色鉛筆', 1200, 'ACTIVE');
INSERT INTO GOODS(CODE, NAME, PRICE, STATUS) VALUES(800, 'マグロ', 3200, 'ACTIVE');

DELETE FROM STOCK;
INSERT INTO STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(100, 10, 'ACTIVE');
INSERT INTO STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(200, 5, 'ACTIVE');
INSERT INTO STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(400, 0, 'ACTIVE');
INSERT INTO STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(500, 0, 'DEACTIVE');
INSERT INTO STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(700, 0, 'ACTIVE');
INSERT INTO STOCK(GOODS_CODE, QUANTITY, STATUS) VALUES(800, 0, 'DEACTIVE');