DROP TABLE GOODS if exists
CREATE TABLE GOODS(ID INTEGER IDENTITY PRIMARY KEY,CODE INTEGER,NAME VARCHAR(20) NOT NULL, PRICE INTEGER, STATUS VARCHAR(10) NOT NULL)
ALTER TABLE GOODS ADD CONSTRAINT UNQGOODS UNIQUE(CODE)

DROP TABLE STOCK if exists
CREATE TABLE STOCK(ID INTEGER IDENTITY PRIMARY KEY,GOODS_CODE INTEGER,QUANTITY INTEGER, STATUS VARCHAR(10) NOT NULL)
ALTER TABLE STOCK ADD CONSTRAINT UNQSTOCK UNIQUE(GOODS_CODE)

DROP TABLE IN_OUT_LOG if exists
CREATE TABLE IN_OUT_LOG(NO INTEGER IDENTITY PRIMARY KEY, IN_OUT_TYPE VARCHAR(10) NOT NULL, GOODS_CODE INTEGER, QUANTITY INTEGER)